### ISSUE TITLE
question: updated info on counter-picks

### ISSUE THREAD

**Issue by iisalazar** [ellysh/dota2-counter-picker#6]
This is more of a question. what's your source for hero information and their counterpicks? 
Really hoping you reply on this one, thanks.

**Comment by ellysh** [comment]
Hello,

I took the information about the counterpicks here:
https://dota2.gamepedia.com/Category:Counters

It can be deprecated because I parsed it ~1 year ago.

**Comment by iisalazar** [comment]
I see, that's all I needed. Thanks
