### ISSUE TITLE
How to get the data

### ISSUE THREAD

**Issue by jaballogian** [ellysh/dota2-counter-picker#7]
Hello,
I really like your application.

Currently, I'm building a dashboard for giving hero draft pick and ban suggestions using React Js.
My purpose is just to test my frontend programming skill using React Js.

We're using the same data source (from https://dota2.fandom.com/) but I just want to know how did you get this data https://github.com/ellysh/dota2-counter-picker/blob/master/dota2picker/database/Database.csv ?
Did you contact them and ask for the data?

Because I'm tired of copying and pasting manually for every hero counters data from the website to my database 😂

**Comment by ellysh** [comment]
Hello,

Thank you for your message!

I did not contact the developers of dota2.fandom.com. Instead, I downloaded all counter picks related pages (https://dota2.fandom.com/wiki/Category:Counters) using the wget utility (https://www.linuxjournal.com/content/downloading-entire-web-site-wget)

Then I wrote a Python script for parsing downloaded pages. The script extracts "Bad against" / "Good against" information based on the frame color. You can find that the red frame matches "Bad against" heroes and the green frame matches "Good against" heroes.

You can repeat my steps and do the same.

**Comment by jaballogian** [comment]
Great idea

Do you still have all the related scripts (the bash/shell that contains wget command and the python script)?

I could add your GitHub account name as the data contributor in my repository https://github.com/jaballogian/dota-2-hero-picking-suggestion if you help me with the data

**Comment by ellysh** [comment]
You can find all Bash and Python scripts to parse dota2.fandom.com pages here:

https://github.com/ellysh/dota2-counter-picker/tree/master/dota2picker/parser

> I could add your GitHub account name as the data contributor

It will be great if you do so.

**Comment by jaballogian** [comment]
Thanks, I will try it soon

**Comment by jaballogian** [comment]
I had successfully run wiki-downloader.sh and all the HTML files had been downloaded into the HTML folder.

Then I ran the wiki-parser.py file but got an error like this:
```bash
Traceback (most recent call last):
  File "C:\<censored>\dota2-counter-picker-master\dota2-counter-picker-master\dota2picker\parser\wiki-parser.py", line 86, in <module>
    main()
  File "C:\<censored>\dota2-counter-picker-master\dota2-counter-picker-master\dota2picker\parser\wiki-parser.py", line 81, in main
    process_file(_HTML_DIR + "/" + hero_name)
  File "C:\<censored>\dota2-counter-picker-master\dota2-counter-picker-master\dota2picker\parser\wiki-parser.py", line 42, in process_file
    for line in f:
  File "C:\Python39\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 1447: character maps to <undefined>
```

I forgot some Python lessons because I haven't used Python for several months 😂

**Comment by jaballogian** [comment]
I copied the error message and found this https://stackoverflow.com/questions/56447543/unicodedecodeerror-charmap-codec-cant-decode-byte-0x81-in-position-49-chara

Then I changed code line 41 into
```python
f = open(filename, encoding='utf-8')
```

I ran again and the error was missing.

**Comment by jaballogian** [comment]
I will close this issue then I will update the readme file in my repository to add your GitHub account name there soon.
